//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.05 at 02:37:43 PM CST 
//


package com.hikvision.ga.commons.datasync.convert;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="data" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="fields">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="field" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="target" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="unique" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                                     &lt;attribute name="default" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="mapping" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="convert" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="params" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="param" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="target" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="defaultValues" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="defaultValue" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="target" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="updateExcludes" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="updateExclude" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="target" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="model">
 *                                       &lt;simpleType>
 *                                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                           &lt;enumeration value="force"/>
 *                                           &lt;enumeration value="conflict"/>
 *                                           &lt;enumeration value="zero"/>
 *                                         &lt;/restriction>
 *                                       &lt;/simpleType>
 *                                     &lt;/attribute>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="valueExcludes" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="valueExclude" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="target" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="typeCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="fullName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="increName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="notifys">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="notify" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="appType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="appCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="relativePath" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="fileSuffix" default="csv">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="csv"/>
 *             &lt;enumeration value="xml"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="encoding" type="{http://www.w3.org/2001/XMLSchema}string" default="UTF-8" />
 *       &lt;attribute name="updateRecoder" type="{http://www.w3.org/2001/XMLSchema}string" default="updateRecoder" />
 *       &lt;attribute name="relativePath" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="cleanHistory" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "data",
    "notifys"
})
@XmlRootElement(name = "dataConvert")
public class DataConvert {

    @XmlElement(required = true)
    protected List<DataConvert.Data> data;
    @XmlElement(required = true)
    protected DataConvert.Notifys notifys;
    @XmlAttribute(name = "fileSuffix")
    protected String fileSuffix;
    @XmlAttribute(name = "encoding")
    protected String encoding;
    @XmlAttribute(name = "updateRecoder")
    protected String updateRecoder;
    @XmlAttribute(name = "relativePath")
    protected String relativePath;
    @XmlAttribute(name = "cleanHistory")
    protected Integer cleanHistory;

    /**
     * Gets the value of the data property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the data property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DataConvert.Data }
     * 
     * 
     */
    public List<DataConvert.Data> getData() {
        if (data == null) {
            data = new ArrayList<DataConvert.Data>();
        }
        return this.data;
    }

    /**
     * Gets the value of the notifys property.
     * 
     * @return
     *     possible object is
     *     {@link DataConvert.Notifys }
     *     
     */
    public DataConvert.Notifys getNotifys() {
        return notifys;
    }

    /**
     * Sets the value of the notifys property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataConvert.Notifys }
     *     
     */
    public void setNotifys(DataConvert.Notifys value) {
        this.notifys = value;
    }

    /**
     * Gets the value of the fileSuffix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileSuffix() {
        if (fileSuffix == null) {
            return "csv";
        } else {
            return fileSuffix;
        }
    }

    /**
     * Sets the value of the fileSuffix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileSuffix(String value) {
        this.fileSuffix = value;
    }

    /**
     * Gets the value of the encoding property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEncoding() {
        if (encoding == null) {
            return "UTF-8";
        } else {
            return encoding;
        }
    }

    /**
     * Sets the value of the encoding property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncoding(String value) {
        this.encoding = value;
    }

    /**
     * Gets the value of the updateRecoder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpdateRecoder() {
        if (updateRecoder == null) {
            return "updateRecoder";
        } else {
            return updateRecoder;
        }
    }

    /**
     * Sets the value of the updateRecoder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdateRecoder(String value) {
        this.updateRecoder = value;
    }

    /**
     * Gets the value of the relativePath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelativePath() {
        return relativePath;
    }

    /**
     * Sets the value of the relativePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelativePath(String value) {
        this.relativePath = value;
    }

    /**
     * Gets the value of the cleanHistory property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCleanHistory() {
        return cleanHistory;
    }

    /**
     * Sets the value of the cleanHistory property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCleanHistory(Integer value) {
        this.cleanHistory = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="fields">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="field" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="target" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="unique" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *                           &lt;attribute name="default" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="mapping" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="convert" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="params" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="param" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="target" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="defaultValues" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="defaultValue" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="target" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="updateExcludes" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="updateExclude" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="target" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="model">
     *                             &lt;simpleType>
     *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                 &lt;enumeration value="force"/>
     *                                 &lt;enumeration value="conflict"/>
     *                                 &lt;enumeration value="zero"/>
     *                               &lt;/restriction>
     *                             &lt;/simpleType>
     *                           &lt;/attribute>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="valueExcludes" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="valueExclude" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="target" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="typeCode" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="fullName" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="increName" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fields",
        "params",
        "defaultValues",
        "updateExcludes",
        "valueExcludes"
    })
    public static class Data {

        @XmlElement(required = true)
        protected DataConvert.Data.Fields fields;
        protected DataConvert.Data.Params params;
        protected DataConvert.Data.DefaultValues defaultValues;
        protected DataConvert.Data.UpdateExcludes updateExcludes;
        protected DataConvert.Data.ValueExcludes valueExcludes;
        @XmlAttribute(name = "typeCode")
        protected String typeCode;
        @XmlAttribute(name = "class")
        protected String clazz;
        @XmlAttribute(name = "fullName")
        protected String fullName;
        @XmlAttribute(name = "increName")
        protected String increName;

        /**
         * Gets the value of the fields property.
         * 
         * @return
         *     possible object is
         *     {@link DataConvert.Data.Fields }
         *     
         */
        public DataConvert.Data.Fields getFields() {
            return fields;
        }

        /**
         * Sets the value of the fields property.
         * 
         * @param value
         *     allowed object is
         *     {@link DataConvert.Data.Fields }
         *     
         */
        public void setFields(DataConvert.Data.Fields value) {
            this.fields = value;
        }

        /**
         * Gets the value of the params property.
         * 
         * @return
         *     possible object is
         *     {@link DataConvert.Data.Params }
         *     
         */
        public DataConvert.Data.Params getParams() {
            return params;
        }

        /**
         * Sets the value of the params property.
         * 
         * @param value
         *     allowed object is
         *     {@link DataConvert.Data.Params }
         *     
         */
        public void setParams(DataConvert.Data.Params value) {
            this.params = value;
        }

        /**
         * Gets the value of the defaultValues property.
         * 
         * @return
         *     possible object is
         *     {@link DataConvert.Data.DefaultValues }
         *     
         */
        public DataConvert.Data.DefaultValues getDefaultValues() {
            return defaultValues;
        }

        /**
         * Sets the value of the defaultValues property.
         * 
         * @param value
         *     allowed object is
         *     {@link DataConvert.Data.DefaultValues }
         *     
         */
        public void setDefaultValues(DataConvert.Data.DefaultValues value) {
            this.defaultValues = value;
        }

        /**
         * Gets the value of the updateExcludes property.
         * 
         * @return
         *     possible object is
         *     {@link DataConvert.Data.UpdateExcludes }
         *     
         */
        public DataConvert.Data.UpdateExcludes getUpdateExcludes() {
            return updateExcludes;
        }

        /**
         * Sets the value of the updateExcludes property.
         * 
         * @param value
         *     allowed object is
         *     {@link DataConvert.Data.UpdateExcludes }
         *     
         */
        public void setUpdateExcludes(DataConvert.Data.UpdateExcludes value) {
            this.updateExcludes = value;
        }

        /**
         * Gets the value of the valueExcludes property.
         * 
         * @return
         *     possible object is
         *     {@link DataConvert.Data.ValueExcludes }
         *     
         */
        public DataConvert.Data.ValueExcludes getValueExcludes() {
            return valueExcludes;
        }

        /**
         * Sets the value of the valueExcludes property.
         * 
         * @param value
         *     allowed object is
         *     {@link DataConvert.Data.ValueExcludes }
         *     
         */
        public void setValueExcludes(DataConvert.Data.ValueExcludes value) {
            this.valueExcludes = value;
        }

        /**
         * Gets the value of the typeCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTypeCode() {
            return typeCode;
        }

        /**
         * Sets the value of the typeCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTypeCode(String value) {
            this.typeCode = value;
        }

        /**
         * Gets the value of the clazz property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getClazz() {
            return clazz;
        }

        /**
         * Sets the value of the clazz property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setClazz(String value) {
            this.clazz = value;
        }

        /**
         * Gets the value of the fullName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFullName() {
            return fullName;
        }

        /**
         * Sets the value of the fullName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFullName(String value) {
            this.fullName = value;
        }

        /**
         * Gets the value of the increName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIncreName() {
            return increName;
        }

        /**
         * Sets the value of the increName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIncreName(String value) {
            this.increName = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="defaultValue" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="target" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "defaultValue"
        })
        public static class DefaultValues {

            @XmlElement(required = true)
            protected List<DataConvert.Data.DefaultValues.DefaultValue> defaultValue;

            /**
             * Gets the value of the defaultValue property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the defaultValue property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getDefaultValue().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link DataConvert.Data.DefaultValues.DefaultValue }
             * 
             * 
             */
            public List<DataConvert.Data.DefaultValues.DefaultValue> getDefaultValue() {
                if (defaultValue == null) {
                    defaultValue = new ArrayList<DataConvert.Data.DefaultValues.DefaultValue>();
                }
                return this.defaultValue;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="target" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "content"
            })
            public static class DefaultValue {

                @XmlValue
                protected String content;
                @XmlAttribute(name = "target")
                protected String target;

                /**
                 * Gets the value of the content property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getContent() {
                    return content;
                }

                /**
                 * Sets the value of the content property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setContent(String value) {
                    this.content = value;
                }

                /**
                 * Gets the value of the target property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTarget() {
                    return target;
                }

                /**
                 * Sets the value of the target property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTarget(String value) {
                    this.target = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="field" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="target" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="unique" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *                 &lt;attribute name="default" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="mapping" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="convert" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "field"
        })
        public static class Fields {

            protected List<DataConvert.Data.Fields.Field> field;

            /**
             * Gets the value of the field property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the field property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getField().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link DataConvert.Data.Fields.Field }
             * 
             * 
             */
            public List<DataConvert.Data.Fields.Field> getField() {
                if (field == null) {
                    field = new ArrayList<DataConvert.Data.Fields.Field>();
                }
                return this.field;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="target" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="unique" type="{http://www.w3.org/2001/XMLSchema}boolean" />
             *       &lt;attribute name="default" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="mapping" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="convert" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "content"
            })
            public static class Field {

                @XmlValue
                protected String content;
                @XmlAttribute(name = "target")
                protected String target;
                @XmlAttribute(name = "unique")
                protected Boolean unique;
                @XmlAttribute(name = "default")
                protected String _default;
                @XmlAttribute(name = "mapping")
                protected String mapping;
                @XmlAttribute(name = "convert")
                protected String convert;

                /**
                 * Gets the value of the content property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getContent() {
                    return content;
                }

                /**
                 * Sets the value of the content property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setContent(String value) {
                    this.content = value;
                }

                /**
                 * Gets the value of the target property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTarget() {
                    return target;
                }

                /**
                 * Sets the value of the target property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTarget(String value) {
                    this.target = value;
                }

                /**
                 * Gets the value of the unique property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Boolean }
                 *     
                 */
                public Boolean isUnique() {
                    return unique;
                }

                /**
                 * Sets the value of the unique property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Boolean }
                 *     
                 */
                public void setUnique(Boolean value) {
                    this.unique = value;
                }

                /**
                 * Gets the value of the default property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDefault() {
                    return _default;
                }

                /**
                 * Sets the value of the default property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDefault(String value) {
                    this._default = value;
                }

                /**
                 * Gets the value of the mapping property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getMapping() {
                    return mapping;
                }

                /**
                 * Sets the value of the mapping property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setMapping(String value) {
                    this.mapping = value;
                }

                /**
                 * Gets the value of the convert property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getConvert() {
                    return convert;
                }

                /**
                 * Sets the value of the convert property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setConvert(String value) {
                    this.convert = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="param" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="target" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "param"
        })
        public static class Params {

            @XmlElement(required = true)
            protected List<DataConvert.Data.Params.Param> param;

            /**
             * Gets the value of the param property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the param property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getParam().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link DataConvert.Data.Params.Param }
             * 
             * 
             */
            public List<DataConvert.Data.Params.Param> getParam() {
                if (param == null) {
                    param = new ArrayList<DataConvert.Data.Params.Param>();
                }
                return this.param;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="target" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "content"
            })
            public static class Param {

                @XmlValue
                protected String content;
                @XmlAttribute(name = "target")
                protected String target;

                /**
                 * Gets the value of the content property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getContent() {
                    return content;
                }

                /**
                 * Sets the value of the content property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setContent(String value) {
                    this.content = value;
                }

                /**
                 * Gets the value of the target property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTarget() {
                    return target;
                }

                /**
                 * Sets the value of the target property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTarget(String value) {
                    this.target = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="updateExclude" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="target" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="model">
         *                   &lt;simpleType>
         *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                       &lt;enumeration value="force"/>
         *                       &lt;enumeration value="conflict"/>
         *                       &lt;enumeration value="zero"/>
         *                     &lt;/restriction>
         *                   &lt;/simpleType>
         *                 &lt;/attribute>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "updateExclude"
        })
        public static class UpdateExcludes {

            @XmlElement(required = true)
            protected List<DataConvert.Data.UpdateExcludes.UpdateExclude> updateExclude;

            /**
             * Gets the value of the updateExclude property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the updateExclude property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getUpdateExclude().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link DataConvert.Data.UpdateExcludes.UpdateExclude }
             * 
             * 
             */
            public List<DataConvert.Data.UpdateExcludes.UpdateExclude> getUpdateExclude() {
                if (updateExclude == null) {
                    updateExclude = new ArrayList<DataConvert.Data.UpdateExcludes.UpdateExclude>();
                }
                return this.updateExclude;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="target" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="model">
             *         &lt;simpleType>
             *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *             &lt;enumeration value="force"/>
             *             &lt;enumeration value="conflict"/>
             *             &lt;enumeration value="zero"/>
             *           &lt;/restriction>
             *         &lt;/simpleType>
             *       &lt;/attribute>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "content"
            })
            public static class UpdateExclude {

                @XmlValue
                protected String content;
                @XmlAttribute(name = "target")
                protected String target;
                @XmlAttribute(name = "model")
                protected String model;

                /**
                 * Gets the value of the content property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getContent() {
                    return content;
                }

                /**
                 * Sets the value of the content property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setContent(String value) {
                    this.content = value;
                }

                /**
                 * Gets the value of the target property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTarget() {
                    return target;
                }

                /**
                 * Sets the value of the target property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTarget(String value) {
                    this.target = value;
                }

                /**
                 * Gets the value of the model property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getModel() {
                    return model;
                }

                /**
                 * Sets the value of the model property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setModel(String value) {
                    this.model = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="valueExclude" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="target" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "valueExclude"
        })
        public static class ValueExcludes {

            @XmlElement(required = true)
            protected List<DataConvert.Data.ValueExcludes.ValueExclude> valueExclude;

            /**
             * Gets the value of the valueExclude property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the valueExclude property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getValueExclude().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link DataConvert.Data.ValueExcludes.ValueExclude }
             * 
             * 
             */
            public List<DataConvert.Data.ValueExcludes.ValueExclude> getValueExclude() {
                if (valueExclude == null) {
                    valueExclude = new ArrayList<DataConvert.Data.ValueExcludes.ValueExclude>();
                }
                return this.valueExclude;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="target" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "content"
            })
            public static class ValueExclude {

                @XmlValue
                protected String content;
                @XmlAttribute(name = "target")
                protected String target;

                /**
                 * Gets the value of the content property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getContent() {
                    return content;
                }

                /**
                 * Sets the value of the content property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setContent(String value) {
                    this.content = value;
                }

                /**
                 * Gets the value of the target property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTarget() {
                    return target;
                }

                /**
                 * Sets the value of the target property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTarget(String value) {
                    this.target = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="notify" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="appType" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="appCode" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="relativePath" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "notify"
    })
    public static class Notifys {

        protected List<DataConvert.Notifys.Notify> notify;

        /**
         * Gets the value of the notify property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the notify property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getNotify().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DataConvert.Notifys.Notify }
         * 
         * 
         */
        public List<DataConvert.Notifys.Notify> getNotify() {
            if (notify == null) {
                notify = new ArrayList<DataConvert.Notifys.Notify>();
            }
            return this.notify;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="appType" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="appCode" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="relativePath" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "content"
        })
        public static class Notify {

            @XmlValue
            protected String content;
            @XmlAttribute(name = "appType")
            protected String appType;
            @XmlAttribute(name = "appCode")
            protected String appCode;
            @XmlAttribute(name = "relativePath")
            protected String relativePath;

            /**
             * Gets the value of the content property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getContent() {
                return content;
            }

            /**
             * Sets the value of the content property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setContent(String value) {
                this.content = value;
            }

            /**
             * Gets the value of the appType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAppType() {
                return appType;
            }

            /**
             * Sets the value of the appType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAppType(String value) {
                this.appType = value;
            }

            /**
             * Gets the value of the appCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAppCode() {
                return appCode;
            }

            /**
             * Sets the value of the appCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAppCode(String value) {
                this.appCode = value;
            }

            /**
             * Gets the value of the relativePath property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRelativePath() {
                return relativePath;
            }

            /**
             * Sets the value of the relativePath property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRelativePath(String value) {
                this.relativePath = value;
            }

        }

    }

}
